### ISSUE TITLE
Configure EMF without XML in EE

### ISSUE THREAD

**Issue by hantsy** [jakartaee/persistence#701]
Persistence 3.2 introduce programmatic APIs for SE env, but for Jakarta EE, we still require persistence.xml to configure Persistence.

Add an annotation similar to the `DataSourceDefinition`:

```java
@EntityManagerFactoryDefinition(
  name = "" // unique for inject by name
  datasource ="",  // or username/password/jdbcUrl
  txType ="LOCAL/JTA",
  qulififiers=[], // for inject by quilifier classes
  properties ={}
)
```

**Comment by gavinking** [comment]
My knee-jerk reaction is that I hate it, just as I similarly hate `@DataSourceDefinition`, but I'm struggling to come up with a _strong_ argument against it.

It's true that we could introduce a `@PersistenceUnitConfiguration` annotation with essentially the same members as the `PersistenceConfiguration` class, but with the addition of the ability to select the CDI scope and qualifiers.

I'm not sure @lukasj would be very keen on this, however, because I don't think he likes seeing more stuff that's specific to the Jakarta EE environment leak into the Persistence spec. I guess if we provided a way to obtain a `PersistenceConfiguration` from a `@PersistenceUnitConfiguration`, then that might deal with that concern.

Dunno, I'm not in love with it at all. Hard to see how it's better than `persistence.xml`.

**Comment by hantsy** [comment]
`@PersistenceUnitConfiguration` is a bit confusing due the existing `PersistenceConfiguration`. I am not sure, but for the current naming convention in the common annotations and other specifications, a `Definition`postfix is used everywhere.

**Comment by gavinking** [comment]
> Ha, I hope all configurations support both annotations and programmatic APIs.

Let me prefix by saying I've been a champion of annotations since before just about anyone else. I mean, we designed EJB3, JPA, and CDI when annotations were still new, and copped a lot of flak at the time from e.g. the Spring community who were at the time incredibly addicted to XML.

But I guess I've never taken it as a requirement that *everything* should be settable in annotations. At least _some things_, for example, database connection properties, just seem to belong naturally in a `.properties` or `.xml` file, or whatever, and I've never really seen a need to move them into the Java code.

If we consider this annotation, the first thing I would ask is: where would you put it? And the natural answer would seem to be: on the module or perhaps package descriptor. It's not clear that that's a more convenient place to have the information than in a `persistence.xml` file.

And then I would ask: what does the actual code look like, and I dunno, YMMV, but I personally have always found complex structured annotations to be quite unsightly. Is this:

```java
@PersistenceUnitConfiguration(name="primaryPU",
    transactionType=PersistenceUnitTransactionType.RESOURCE_LOCAL,
    classes={Book.class, Author.class},
    properties={
        @Property(name="hibernate.connection.driver_class" value="org.h2.Driver"),
        @Property(name="hibernate.connection.url"  value="jdbc:h2:mem:db1"),
        @Property(name="hibernate.connection.username" value="sa"),
        @Property(name="hibernate.connection.password" value=""),
        @Property(name="hibernate.hbm2ddl.auto" value="create-drop"),
        @Property(name="hibernate.show_sql" value="false")
    }
)
package org.example;
```

really an improvement on this:

```xml
<persistence>
    <persistence-unit name="primaryPU" transaction-type="RESOURCE_LOCAL">
        <class>org.example.Book</class>
        <class>org.example.Author</class>
        <properties>
            <property name="hibernate.connection.driver_class" value="org.h2.Driver"/>
            <property name="hibernate.connection.url" value="jdbc:h2:mem:db1"/>
            <property name="hibernate.connection.username" value="sa"/>
            <property name="hibernate.connection.password" value=""/>
            <property name="hibernate.hbm2ddl.auto" value="create-drop"/>
            <property name="hibernate.show_sql" value="false"/>
        </properties>
    </persistence-unit>
</persistence>
```

To my eyes it's, if anything, worse.

I dunno, I mean, it's not _terrible_, but whatever advantages it might have are just not apparent to me.

**Comment by hantsy** [comment]
> But I guess I've never taken it as a requirement that everything should be settable in annotations. At least some things, for example, database connection properties, just seem to belong naturally in a .properties or .xml file, or whatever, and I've never really seen a need to move them into the Java code.

I like the environment-aware *properties* and Java configuration(similar to CDI bean producers) that Spring Boot currently does. But *Jakarta Config* is not ready at the moment.

> If we consider this annotation, the first thing I would ask is: where would you put it?

I think the package level and application scoped CDI beans, like the `@DataSourceDefinition`.

> I dunno, I mean, it's not terrible, but whatever advantages it might have are just not apparent to me.

A consistent programming model and more options for developers (**declarative** approaches like annotations or XML and **programmatic** *builder/factory* APIs) are good things. 

* Let developers decide the method to define the `EntityManagerFactory`/`Persistence Unit` using annotations(an alternative of XML) or programmatic APIs(like the current `PersistenceConfig`). 
* To align with other specifications in Jakarta EE, providing similar APIs(like the `DataSourceDefinition`, and similar annotations in JMS, Security, Conncurrency, etc.) is easy to accept by new developers.

**Comment by trajano** [comment]
> But I guess I've never taken it as a requirement that _everything_ should be settable in annotations. At least _some things_, for example, database connection properties, just seem to belong naturally in a `.properties` or `.xml` file, or whatever, and I've never really seen a need to move them into the Java code.

Though not necessarily annotations, I would prefer that everything should be settable by code primarily so we can create unit/integration/MVCE tests without too many files to prove or disprove some code.

**Comment by hantsy** [comment]
>Look, I'm not implacably against this; I'm just not sure that this is where I would spend our complexity budged.

As mentioned, in the end user's view, I wish:

* there are `more options` for developers, declarative annotations (the proposal/request in this issue)/xml (persistence.xml already exists since it was born) and programmatic API (the configuration API is provided in 3.2)
* and a `consistent` programming model **across all specs**. We have a collection of `XXXDefinition` to define data source, JMS factory/destination, concurrency executor service, security. It is reasonable to add a something like `@EntityManagerFactoryDefinition` in the persistence to follow this convention.

**Comment by sebersole** [comment]
> > But I guess I've never taken it as a requirement that _everything_ should be settable in annotations. At least _some things_, for example, database connection properties, just seem to belong naturally in a `.properties` or `.xml` file, or whatever, and I've never really seen a need to move them into the Java code.
> 
> Though not necessarily annotations, I would prefer that everything should be settable by code primarily so we can create unit/integration/MVCE tests without too many files to prove or disprove some code.

I'm curious - do you see a specific gap currently where this is not the case?  Something concrete we can discuss; stuff that is amorphic we obviously cannot.

**Comment by OndroMih** [comment]
Isn’t it better to use CDI and produce an EMF created using Java SE API, which can be easily injected? 

Recently, we’ve been pusing for CDI-based solutions in Jakarta EE, which allow flexibility and integrate well together. In fact, @DataSourceDefinition and similar annotations could be easily turned into a CDI producer, if we introduced a definition class/record that matches it and allow creating the definition by a producer.

CDI producers are much more flexible than annotations, properties, XML, unless we introduce support for expressions for all fields as Jakarta Security supports in annotation fields. The only “disadvantage” is that it’s not declarative and not possible to visualize or override in some admin console. But is that still a value? Do people take advantage of the declarative character of annotation or XML?

**Comment by gavinking** [comment]
> Recently, we’ve been pusing for CDI-based solutions in Jakarta EE, which allow flexibility and integrate well together. In fact, `@DataSourceDefinition` and similar annotations could be easily turned into a CDI producer, if we introduced a definition class/record that matches it and allow creating the definition by a producer.

That's more or less what we've already done in EE 11, where we've said that any persistence unit implicitly defines a bunch of beans which are injectable via CDI. (We don't say they're producer methods; they might be contributed by a portable extension or whatever, but that's effectively the same.)

But that's not really what this issue is asking for. CDI doesn't define any place to specify configuration info like JDBC URLs,  usernames, passwords, connection pool sizes, etc.

**Comment by gavinking** [comment]
@trajano 

> Though not necessarily annotations, I would prefer that everything should be settable by code primarily so we can create unit/integration/MVCE tests without too many files to prove or disprove some code.

Well I believe this use case was already solved in JPA 3.2 by the addition of `PersistenceConfiguration`.

**Comment by hantsy** [comment]
> CDI producers are much more flexible than annotations, properties, XML, unless we introduce support for expressions for all fields as Jakarta Security supports in annotation fields. The only “disadvantage” is that it’s not declarative and not possible to visualize or override in some admin console. But is that still a value? Do people take advantage of the declarative character of annotation or XML?

As I mentioned in the comment here https://github.com/jakartaee/persistence/issues/701#issuecomment-2726144273. As an end user/developer, we just wish there is a **united programming model** provided in various Jakarta EE specifications. 

CDI producers are also good, I do not object to it. I maybe prefer this approach if there is no existing annotations like DataSourceDefintion, XXXDefition.

(Also, based on CDI build API and AOT in Java 25, if possible provides the hard way to erase all annotations.
All AOT solutions in Spring/Micronaut are trying to replace the annotations and reflections codes with pure Java codes at compiling time before building the native images.)

**Comment by gavinking** [comment]
> As I mentioned in the comment here https://github.com/jakartaee/persistence/issues/701#issuecomment-2726144273. As an end user/developer, we just wish there is a united programming model provided in Jakarta EE.

I would say that the unified model for this stuff is supposed to be the Config spec. I understand that it's had a troubled history, but I'm not convinced the problem is really all that hard, and I think it's reasonable to hope for a decent solution in the future.

**Comment by hantsy** [comment]
Yeah, I hope Config can resolve all configuration-related issues, but it is still not released yet, no one can ensure it is 100% included in the Jakarta EE 12. 

But XXXDeniftion existed in Jakarta EE for a few years, this annotations style we are familiar with is used from Jakarta Annotations(DataSourceDefition) to Messaging, Security, etc.

**Comment by OndroMih** [comment]
> Well I believe this use case was already solved in JPA 3.2 by the addition of `PersistenceConfiguration`.

I agree. JPA 3.2 already allows defining a producer for `EntityManager` or `EntityManagerFactory`, with the help of `PersistenceConfiguration`. So it's possible to do this in an app:

```
@Produces @ApplicationScoped 
EntityManagerFactory configure() { ... }

@Produces 
EntityManager create(EntityManagerFactory factory) {
    return factory.createEntityManager();
}

void close(@Disposes EntityManager entityManager) {
    entityManager.close();
}
```

And then:

```
@Inject
EntityManager em;
```

I'm not sure if it's possible to inject `em` just with the `EntityManagerFactory` producer, skipping the producer and disposer for `EntityManager`. Do you know, @gavinking ?

**Comment by gavinking** [comment]
> I'm not sure if it's possible to inject em just with the EntityManagerFactory producer, skipping the producer and disposer for `EntityManager`. 

No, because you need quite a lot of information in order to manage the lifecycle of a transaction-scoped `EntityManager`.

Your implementation above looks wrong without `@RequestScoped` or `@TransactionScoped` or whatever.

**Comment by hantsy** [comment]
@OndroMih With Jakarta Persistence 3.2, the `EntityManager/EMF` is already available to be injected like other CDI beans in a Jakarta EE environment.

**Comment by gavinking** [comment]
> [@OndroMih](https://github.com/OndroMih) With Jakarta Persistence 3.2, the `EntityManager/EMF` is already available to be injected like other CDI beans in a Jakarta EE environment.

Correct. Though it's mostly a feature of Jakarta EE 11, rather than of Persistence 3.2 itself.

(I assumed we were talking about standalone.)

**Comment by OndroMih** [comment]
@gavinking 

> No, because you need quite a lot of information in order to manage the lifecycle of a transaction-scoped EntityManager.

I suppose this comment assumes Java SE environment, where it's true. In Jakarta EE, the container already knows enough and can simply inject EntityManager based on information in `persistence.xml`. So I think that the Jakarta Platform spec could define that, if there's no persistence unit defined in persistence.xml, it would retrieve EMF from CDI. 

> Your implementation above looks wrong...

Correct. I provided the simplest example that illustrates the idea, not a complete example.

**Comment by OndroMih** [comment]
@hantsy 

> @OndroMih With Jakarta Persistence 3.2, the EntityManager/EMF is already available to be injected like other CDI beans in a Jakarta EE environment.

Yes, EM/EMF is available to be injected, but only if a corresponding persistence unit is defined in `persistence.xml`. If there's no `persistence.xml`, nothing would be injected. If an app defines a CDI producer for EMF, EM/EMF could be injected based on the produced EMF, even without `persistence.xml`. I thought that this is what you aimed for with this issues, although using annotations instead of a CDI producer.

**Comment by hantsy** [comment]
> EM/EMF could be injected based on the produced EMF, even without persistence.xml


If CDI provides an autodetect/autoconfigure mechanism like Spring Boot, this is possible via the persistence/CDI integratoin module.

* Produces EM/EMF by default if a Persistence provider in the classpath or modulepath.
* Optionally allow developers to configure properties via Config/application.properties
* Optionally allow developers to declare a PersistenceUnitConfiguration bean.

**Comment by gavinking** [comment]
@hantsy Again, with only JPA and CDI, injection of the EM is impossible. We have to know something about the  transaction or request.

The comparison to Spring Boot is not apt, since Spring Boot is a whole application container with contextual transaction management.

**Comment by hantsy** [comment]
@gavinking I realize including a `EntityManagerFactoryDefiniton` has another reason, in the [DataSourceDefinition javadoc](https://docs.oracle.com/javaee/7/api/javax/annotation/sql/DataSourceDefinition.html), and other docs, these resources are described as container managed resource, which introduced in Java EE 7, to replace the hard configuration via application server administration UI.

And when starting WildFly and deploying applications, I also realized the XXXDefintions are handled earlier that other application beans when the application is being deployed. And WildFly also exposed EMF via JDNI at application deployment.

I am not sure these resources are designed as shared resources in a domain or crossing domains in a application server.

Like Persistence/CDI integration, this `EntityManagerFactoryDefiniton` handling could be part of Jakarta EE integration.

**Comment by gavinking** [comment]
> And when starting WildFly and deploying applications, I also realized the XXXDefintions are handled earlier that other application beans when the application is being deployed. And WildFly also exposed EMF via JDNI at application deployment.

If what you mean is that the EMF instantiation happens really early in WildFly, that's true, but it's hugely problematic, and it's something we're trying to change via https://github.com/jakartaee/persistence/issues/650.

**Comment by gavinking** [comment]
Just for the record, here's what I guess this annotation would look like if we ever did decide to add it:

```java
@Retention(RetentionPolicy.RUNTIME)
@Target(ElementType.MODULE)
public @interface PersistenceUnitDefinition {
    String name() default "";
    PersistenceUnitTransactionType transactionType() default JTA;
    String description() default "";
    String provider() default "";
    Class<? extends Annotation> scope() default Annotation.class;
    Class<? extends Annotation>[] qualifiers() default {};
    String jtaDataSource() default "";
    String nonJtaDataSource() default "";
    String[] jarFileUrls() default {};
    String[] mappingFileNames() default {};
    String[] classes() default {};
    boolean excludeUnlistedClasses() default false;
    SharedCacheMode sharedCacheMode() default UNSPECIFIED;
    ValidationMode validationMode() default AUTO;
    FetchType defaultFetchType() default EAGER;
    SchemaManagementAction schemaManagementDatabaseAction() default NONE;
    SchemaManagementAction schemaManagementScriptsAction() default NONE;
    PersistenceProperty[] properties() default {};
}
```

Note that it's a bit different from `PersistenceConfiguration`, which is directed towards the non-container usage, whereas this is intended to set up a container-manager persistence unit which gets instantiated using `PersistenceProvider.createContainerEntityManagerFactory(PersistenceUnitInfo, Map)`.

I'm still not really seeing the value of this but if someone like @starksm64 wants to speak up in favor of it, I don't think it's a *problem* to add.

**Comment by gavinking** [comment]
Well, I guess I realized that I *can* imagine myself wanting to write something like this:

```java
@PersistenceUnitConfiguration(name="Library",
    transactionType = RESOURCE_LOCAL,
    classes = {Book.class, Author.class, Publisher.class},
    excludeUnlistedClasses = true, // faster startup (no scanning)
    nonJtaDatasource = "java:/comp/env/libraryData"
    qualifiers = Library.class,
    defaultFetchType = LAZY,
    schemaManagementDatabaseAction = VALIDATE,
    properties={
        @Property(name="hibernate.type.java_time_use_direct_jdbc" value="true"),
        @Property(name="hibernate.type.prefer_native_enum_types" value="true"),
        @Property(name="hibernate.use_identifier_rollback" value="true"), 
        @Property(name="jakarta.persistence.jdbc.batchSize"  value="20")
    })
module org.example { ... }
```

on the condition that the container let me easily override other settings at deployment time. For example, perhaps I need to override the `batch_size` I set there as a default, or even the datasource name, or maybe in a test deployment I want to switch the schema management action to `CREATE`.

And, in fact, the Persistence spec actually anticipates this need, and *does* define a way to do at least most of this sort of overriding as part of the container/provider contract.

So I guess my question for @scottmarlow, @njr-11, @bstansberry, and @arjantijms is: do WildFly and Liberty and other true EE containers actually expose this to the user and provide a nice way to override the information in `persistence.xml` (or, potentially, in this annotation) at deployment time?

**Comment by gavinking** [comment]
Note that the analogy with `@DataSourceDefinition` is actually quite misleading, since `DataSourceDefinition` really does define a bunch of stuff that is completely deployment-specific, and so it's really a very dumb approach. But `@PersistenceUnitConfiguration` does have some things in there which _aren't_ specific to the deployment, or, at least, can provide reasonable default values across deployments.

Also`@DataSourceDefinition` is `@Target({ElementType.TYPE})` what the fuck?

Anyway, let's just forget about `@DataSourceDefinition` since it's obvious garbage, and focus on the feature requested here, which may not be, because I might have been too quick in pouring cold water on it, @hantsy.

**Comment by gavinking** [comment]
One thing I want to make clear in what I'm toying with here:

- `@PerisistenceUnitConfiguration` (or maybe `@PerisistenceUnitDefinition` as originally suggested) would be intended for use in a Jakarta EE container app, whereas
- `PersistenceConfiguration` is for Java SE.

I am not sure if we can make `@PerisistenceUnitConfiguration` work with `Persistence.createEntityManagerFactory(String persistenceUnitName)` because in SE usage we don't do scanning for annotations. Perhaps we could make it work by saying that the name of the persistence unit is derived from the module name by some well-defined mapping, eg, `org/example` in the example above.

**Comment by arjantijms** [comment]
> So I guess my question for @scottmarlow, @njr-11, @bstansberry, and @arjantijms is: do WildFly and Liberty and other true EE containers actually expose this to the user and provide a nice way to override the information in

For Eclipse GlassFish and Eclipse Piranha the plan of sorts is to support placeholders (${} syntax) in known deployment desciptors and annotations, AND target specific annotations with a path syntax. E.g. along the lines of 

```
org.OmniFish.example.MyClass.foo.bar=12
```

Using microprofile config to define and also to resolve.

(Note that Jakarta Security officially supports Expression Language in the attributes of all its annotations, which are allowed to resolve to container / deployment resources)

**Comment by gavinking** [comment]
OK, thanks for the info. Neither of those things is really the sort of thing I was thinking of.

I was looking for something more along the lines of being able to say "for this persistence unit with this given name, set these properties".

Because the Persistence spec already has a [well-defined way](https://jakarta.ee/specifications/persistence/3.2/jakarta-persistence-spec-3.2#a13443) for the container to pass a bunch of overrides to the provider along with the `PersistenceUnitInfo`.

And because writing something like:

```java
    nonJtaDatasource = "${Library.datasource.name}"
```

in an annotation is just silly and buys me nothing. We shifted a standard config property `jakarta.persistence.jtaDataSource` into an annotation and then we shifted it back out again into a non-standard config property. And we had to use a string-embedded minilanguage to do it. Awesome. What?

**Comment by OndroMih** [comment]
I think you misunderstood, @gavinking . The expression as @arjantijms suggested, isn’t supposed to be a custom config property. It should an EL expression, like in JSF, that rederences a @Named CDI bean and its methods or getters. It’s already supported in Jakarta Security annotations and would be good to support it across all Jakarta APIs. This allows providing the configuration programmatically, from within application, which can apply various rules to produce the final value (e.g. it can provide different config for produce the or test env)

Though, this probably not what seek, @gavinking . It doesn’t provide a standard way of overriding the config in the container - the app would need to allow that in the named CDI bean and it would be in a non-standard way.

**Comment by OndroMih** [comment]
Another option, which suits your desired usecase, is the one which @arjantijms mentioned later - enable overriding annotation values by config properties. This would allow setting config properties in external config sources, such as system properties, to override the values in the code.

This requires 2 things in Jakarta EE:
- specify a common source of configuration properties (right now it might be system properties, lter Jakarta Config or MicroProfile Config, if it’s moved under Jakarta)
- define a common way how to derive property key, so that it exactly matches the annotation value it should override. For PersistenceUnit, it could just be like unitname.jtaDatasource, or appname.unitname.jtaDatasource to support multiple applications. For more general cases, the key could be derived from the annotation class name and package

**Comment by gavinking** [comment]
> The expression as @arjantijms suggested, isn’t supposed to be a custom config property. It should an EL expression, like in JSF, that rederences a @nAmed CDI bean and its methods or getters. 

Sure, I get that. But the problem I'm trying to solve is how to override things specified statically in an annotation with deployment-specific configuration. That CDI bean would have to get the info from somewhere deployment-specific, as you say:

> external config sources, such as system properties

What I'm saying is I don't need EL (or CDI) as a middleman here. I want that external config / system properties passed directly to `PersistenceProvider.createContainerEntityManagerFactory(PersistenceUnitInfo, Map)` in that `Map`.

> define a common way how to derive property key, so that it exactly matches the annotation value it should override. For PersistenceUnit, it could just be like unitname.jtaDatasource, or appname.unitname.jtaDatasource to support multiple applications. For more general cases, the key could be derived from the annotation class name and package

I really don't need any of that, since the spec _already defines the names of these properties_, and has since JPA 1.0.

https://jakarta.ee/specifications/persistence/3.2/jakarta-persistence-spec-3.2#a13443

**Comment by hantsy** [comment]
What I requested is defining an EMF (implicitly a respective EM) `Jakarta EE container managed` resource with annotations, also exposed as CDI beans. This allows developers to use the existing consistent experience to define container managed resources, which are resolved and prepared at deployment time. 

EL support should be expanded to all existing `XXXDefitiion`, esp. `@DataSourceDefinition`, etc. 

I do not think the EL support is related to Jakarta Config. 

Of course, Jakarta Config and the properties used in a certain specification provide a way to configure them in a centralized place (via config provider, files, secret storage etc.).

`PersistenceUnitConfiguraiton` is a good alternative for the traditional `peristence.xml`. But it is not conflict that provided a `@EntityManagerFactoryDefition` annotation to define container managed `EntityManagerFactory/EntityManager` resource.

But `PersistenceUnitConfiguration` can not replace `Jakarta Config` or `EL` support. 

I wish all Jakarta EE specifications can provide consistent experience for developers.

**Comment by gavinking** [comment]
OK, so let me set an expectation here. 

We are definitely not going to do EL support🤢 in annotations, so just forget about that one. You all already know what I think of programming with strings, so I'm pretty sure you can imagine why putting an expression language inside strings is simply a non-starter with me.

I like Java because of its type safety. I don't like things which undermine the type safety of Java.

**Comment by gavinking** [comment]
> It should an EL expression, like in JSF, that references a ... CDI bean 

I mean, I created CDI with the specific goal of getting away from the Spring framework way of identifying dependencies via untypesafe names of bean definitions written in XML. Yes, we did provide the `@Named` annotation to allow integration with templating technologies like Facelets written in languages with no type safety, but right from the start we told everyone that `@Named` was not an invitation to go around using the names in Java code.

At that time nobody had had the "bright" idea of leaking EL into Java annotations. EL was for templating languages.

**Comment by OndroMih** [comment]
I agree with you @gavinking , let’s not go into disputes here. EL usage in Security API is there just because Java lacks the ability to support method references in annotations to provide a programmatic way supplying configuration. But that would be for another debate.

Here, I don’t get what you mean by standard JPA properties. Yes, there are standard properties, but only scoped to a specific persistence unit. So they could be defined inside a PU definition in persistence.xml or in a map in an annotation. If you want to define them externally and the app has multiple PUs or container has multiple apps, then you also need to define the properties in way that it’s clear to which PU in which app the refer to.

So, at least with an app.puname prefix, like this:

myapp.mypu.jakarta.persistence.jtaDatasource=myDS

Does that make sense now? The app prefix should be unified IMHO for all specs. The PU name part eould be defined in the Persistence spec, and the rest is standard PU properties that are already defined.

**Comment by gavinking** [comment]
> EL usage in Security API is there just because Java lacks the ability to support method references in annotations to provide a programmatic way supplying configuration. 

Here we use the static metamodel for that.

`@OneToMany(mappedBy=Book_.AUTHORS)`

But sure, that approach might not work well in other contexts.

> Yes, there are standard properties, but only scoped to a specific persistence unit. So they could be defined inside a PU definition in persistence.xml or in a map in an annotation. If you want to define them externally and the app has multiple PUs or container has multiple apps, then you also need to define the properties in way that it’s clear to which PU in which app the refer to.

What I'm saying is that I want containers to give me some way to declare the persistence unit in a `persistence.xml`, or in that annotation `@PersistenceUnitDefinition` or whatever. But then I want to be able to write some deployment-specific configuration that overrides those defaults, something like, I dunno, picking a crap syntax:


```toml
[PersistenceUnit/Library]

jakarta.persistence.jtaDataSource = java:/comp/env/datasouce
jakarta.persistence.jdbc.fetchSize = 1000
```

**Comment by OndroMih** [comment]
If you mean [PersistenceUnit/Library] is a prefix or section name for properties, then we’re on the same page. My example was for using properties files or system properties, your example is in TOML format or something similar. Right now, Jakarta EE doesn’t specify any configuration sources, so only standard  Java sources xan be used (system properties, env vars), and maybe JNDI. Once Jakarta EE adopts some Config spec, those properties could be defined via other sources as well.

**Comment by gavinking** [comment]
> Right now, Jakarta EE doesn’t specify any configuration sources, so only standard Java sources can be used (system properties, env vars), and maybe JNDI.

Right, and neither system properties nor environmental variables work for the problem of passing properties to a certain persistence unit.

> Once Jakarta EE adopts some Config spec, those properties could be defined via other sources as well.

Last time I looked at the Config spec, it seemed to be very focussed on defining an API for applications to access configuration information, and not on the problem of providing configuration that *containers* (or in this case, the persistence provider) understand.

And yet, configuring container infrastructure is an *extremely* common problem.

On the other hand, we don't particularly need a *standard* approach to be able to move forward with something like what is proposed here; we just need to know that containers provide *some reasonable way* to do such things, even if it's something completely vendor-specific.

So the question was really: do containers today provide any reasonable way to populate the `Map` argument of this method with properties specified by the user at deployment time:

```java
public interface PersistenceProvider {
    EntityManagerFactory createContainerEntityManagerFactory(PersistenceUnitInfo info, Map<?, ?> map);
}
```

[Note: the properties in that `Map` are **not** the properties defined in `persistence.xml`. The properties in `persistence.xml` are obtained from `PersistenceUnitInfo.getProperties()`. These properties _override_ stuff specified in `persistence.xml`.]

**Comment by OndroMih** [comment]
Why would users need to pass those properties? They are integration properties and they are meant to be container specific and defined by the container. Users would need to pass these properties only if they want to create their own container or bypass the default components  provided by the provider, e.g. use their own validator. I thought we’re talking about overriding properties that the user can already hardcode in the app.

Anyway, in either case, Jakarta Config or MicroProfile Config are well usable in containers. The only problem is to map global config sources to specific applications or modules. E.g. if a config property name is mypu.jakarta.persistence. jtaDatasource, then typically a system property of that name would apply to every application that contains a PU named mypu. The Config spec could define how to add an application specific prefix to route the configuration to a specific application.

At the current state of things, it could be enough that JOA specifies config properties wothout any application prefix, e.g. PUNAME.jakarta.persistence.jtaDatasource, without defining the source of the configuration. Containers could provide their own source and would at least use the standard properties in their container-specific way. Some might use MicroProfile Config and allow adding app-specific prefix in their own way, until this is standardized.

**Comment by gavinking** [comment]
> Why would users need to pass those properties? They are integration properties and they are meant to be container specific and defined by the container. 

I know that the Javadoc calls them "integration-level properties", but it doesn't define what an "integration-level property" is, and given that it also says they can control schema generation, they must be at least somewhat specific to the deployment. Our implementation&mdash;which I personally had nothing to do with, FTR&mdash;treats them just like the similar `Map` argument that gets passed to `createEntityManager()`. (I checked.) I predict that other JPA implementations do a similar thing.

And the spec also goes to [great lengths](https://jakarta.ee/specifications/persistence/3.2/jakarta-persistence-spec-3.2#a13443) in section 9.7 to define a bunch of properties which override XML elements in `persistence.xml`, and others which override properties specified in `persistence.xml`. Whatever the original intent, it does not seem sensible that all those properties are only for use in the Java SE environment! Like ... just not sensible at all.

And I don't actually care at all about the original intention. It's a literal two line change to the spec to clarify this and say very clearly that the `Map` can contain any of the properties defined in section 9.7, and not just "integration-level properties", whatever that might mean.

What I'm saying is that *there is just no point adding [this requested feature](https://github.com/jakartaee/persistence/issues/701)* if there's no way to override the configuration and specify additional settings, or overrides.

> The only problem is to map global config sources to specific applications or modules

Exactly, that's precisely the point I was making above.

> The Config spec could define how to add an application specific prefix to route the configuration to a specific application.

Well of course it should. I mean, if we expect it to be actually useful for something.

>  Containers could provide their own source and would at least use the standard properties in their container-specific way. Some might use MicroProfile Config and allow adding app-specific prefix in their own way, until this is standardized.

Right, and this is why I directed my original question about this to @starksm64 and @njr-11, because I wanted to understand what capabilities WildFly and Liberty offer today. As I said, it doesn't have to be standard, as long as it's *something*. But if it's *nothing*, there's just no point in providing any sort of annotation to declare a persistence unit. I have never in my life heard of someone not having deployment-specific configuration for a PU.

**Comment by gavinking** [comment]
Alright, so I had an idea for how to do something sensible here, and it's so simple I'm not sure why it didn't occur to me earlier; I was being a bit dense.

So the idea is the following: we let you specify property overrides for a persistence unit declared in the `persistence.xml` file, or using this new `@PersistenceModule` annotation, in a file with the name `META-INF/UnitName.properties`.

That's not perfect, but it's at least not worse than `persistence.xml`, and it opens the door to containers being more flexible about where those property overrides can be sourced from.

And I think it is quite natural that if you're working with the Java module system that you would _declare_ that this is a persistence module (which is what a persistence unit really is, a module) in the `module` descriptor.

My only question then is: today, a `persistence.xml` file is permitted to declare multiple persistence units in the same module. But the natural and elegant way of thinking about this here is that `@PersistenceModule` is *not* a repeatable annotation, and that there's a one-to-one relationship between modules and persistence units. But, I have no doubt that some people are going to complain that this is less flexible than they would prefer. Should I pay attention to such people?

**Comment by gavinking** [comment]
@hantsy Here is a proposal: https://github.com/jakartaee/persistence/pull/861

**Comment by arjantijms** [comment]
> We are definitely not going to do EL support🤢 in annotations, so just forget about that one. You all already know what I think of programming with strings

Irregardlless of whether I would like to see EL support in Persistence annotations or not (I was only saying Security had that), this is perhaps a prime example of what is maybe by far the greatest problem in all of EE.

We should be a uniform platform, but because it's me (more or less) sitting on Security, Nathan on e.g. Transactions and you on Persistence, we get incoherent APIs. 

One of us hated statics, so that API had no statics, another loved statics so the API has tons of statics. You hate Expression Language, I love it. Then we have JNDI in one spec (because someone there loved JNDI and hated, really hated with a passion CDI), while another spec has only CDI (because someone there hated JNDI and loved CDI). In one spec something is called JTA, since on that spec someone thinks fully written words are unreadable, and another spec uses "Jakarta Transactions" since on that spec someone thinks abbreviations are obscure.

Meanwhile we have a user who gets to use the EE platform, but constantly has to shift between technologies and mental models.

**Comment by arjantijms** [comment]
> At that time nobody had had the "bright" idea of leaking EL into Java annotations. EL was for templating languages.

Meh, at the same time Expression Language was extracted to a standalone spec, with a specific goal for broad adoption accross the platform.

**Comment by gavinking** [comment]
@arjantijms I'm not sure what you're proposing to do about that.

Also: while we are indeed working very hard here on improving integration with other Jakarta specifications and with the whole platform, I hope you understand that Jakarta Persistence is used more _outside_ the Jakarta platform than in it. And this was always the case: unlike some other Jakarta specifications, *this specification* always had well-defined APIs for usage in Java SE, _and it's real name is therefore the Java Persistence API_. It is just not a Jakarta-specific thing. Lukas in particular was very fussy about avoiding unnecessary entanglements with other technologies when not absolutely necessary; I intend to carry on that legacy. This spec needs to say things that are sensible in Jakarta EE, for sure, but the things is says also need to be sensible in Quarkus (think: everything done at build-time), in Micronaut, and, much as it hurts me all the way to my bone marrow to say it, in Spring.

**Comment by OndroMih** [comment]
@gavinking , I think what @arjantijms meant to say is that, if there's something that other specs in Jakarta EE do, it makes sense to support if in Persistence, whether some people like it or not. JPA is also a perfect example of a spec that is very well separated into Java SE part and EE part. In the EE part, we can afford to define things that are specific for containers. without impacting the majority that uses JPA in SE.

As an example, if Security, JSF, and other specs use EL, JPA should consider using them, at least in the EE part. Even if it's not a recommended and cleanest pattern, it makes the whole Jakarta EE more coherent. And it makes everybody happy - those that favor Java SE, can use a pattern more suitable, albeit specific to JPA, while those that favor containers and Jakarta EE, could use familiar patterns across multiple specs.

We should be able to find some consensus and respect others, not fight against each other just because we have a firm view on things. Specifications are about finding common grounds, while implementations are to allow stricter, maybe even cleaner and more opinionated functionality. Don't you agree?

**Comment by gavinking** [comment]
> Don't you agree?

I don't agree that the Persistence spec needs EL in it, no.

Now, look, the idea of shoehorning EL into the Persistence spec is just OT for this discussion, which is supposed to be about @hantsy's request for an annotation-based alternative to `persistence.xml`. That's my fault for engaging with what I should have just ignored, so I ask your forgiveness for that. Anyway, I would now like to request that you guys please take the OT discussions somewhere else so we can focus on the substance of this issue. 🙏

**Comment by gavinking** [comment]
Yesterday I said:

> I am not sure if we can make `@PerisistenceUnitConfiguration` work with `Persistence.createEntityManagerFactory(String persistenceUnitName)` because in SE usage we don't do scanning for annotations. Perhaps we could make it work by saying that the name of the persistence unit is derived from the module name by some well-defined mapping, eg, `org/example` in the example above.

And the question is: does tying `@PersistenceUnit` to a module descriptor solve that problem?? Can the `Persistence` class find that annotation on the module descriptor in the SE use case?

It looks like maybe it *does* solve the problem, because I can iterate over the modules  in `ModuleLayer.boot().modules()` and inspect their annotations.  But since I have literally never used this module system before, I don't know what monsters are lurking there.

So it might be better to just say that any persistence unit declared using `@PersistenceModule` shares the name of the model. Which is a very sane and reasonable thing to say anyway.

**Comment by arjantijms** [comment]
>  It is just not a Jakarta-specific thing.

It maybe goes a bit offtopic, but the underlying question is perhaps why specs that don't really have their heart fully in Jakarta are actually part of Jakarta?

Taking it one more step further, what actually IS a Jakarta thing in this context? Is it, for instance, the assumption that CDI is available? But we can add CDI to Java SE just as well.

**Comment by hantsy** [comment]
It looks the `@PersistenceModule` is a little different from the current `@DataSourceDefinition`, etc. 

As mentioned before, I wish there is a consistent experience for these annotations of preparing the container resources (also exposed as CDI beans) at deployment time, or module loading time if JPMS is used like doc of `@PersistenceModule`.

**Comment by gavinking** [comment]
> It looks the `@PersistenceModule` is a little different from the current `@DataSourceDefinition`

Well, yes, of course! Because a persistence unit is not like a container-managed datasource!

A **datasource definition**:

-  comprises a list of configuration properties like its JNDI name, JDBC URL, a username and password, port number, parameters for controlling connection pooling, and so on;
- is specific to a given deployment of the system (those configuration parameters are always different between test/staging/prod, because test/staging/prod do not use the same database);
- has no associated application developer-written code; and
- is not in any meaningful sense packaged as a "module", nor is it any meaningful sense a "component" of the application.

[Of course, it doesn't make any sense to put any of that information in an annotation, and that's why, at least as far as I know, essentially nobody uses `@DataSourceDefinition` except in toy examples.]

A **persistence unit**:

- is a package of user-written code comprising tens to hundreds of annotated managed entity classes and supporting code, together with "configuration" information of various sorts;
- some of the "configuration" information is completely static and does not vary between deployments: mapping annotations, one or more `orm.xml` files, lists of entities, certain config properties like `JTA` vs `RESOURCE_LOCAL` transaction management or CDI qualifiers, but
- other configuration information is deployment-specific or at least potentially deployment-specific: the schema management action, and datasource-related configuration, and so on; and
- is quite clearly a "module" in all but name (early on we were using the term "persistence archive" for a jar with a `META-INF/persistence.xml`, but at some stage that term appears to have fallen out of use and right now it only occurs in the XSD).

These two things are not the same kind of thing.

Look, folks, I appreciate that you guys have taken some time to comment here and make suggestions, but I would ask that in future you spend more time **thinking** than commenting. We're not going to put anything into the persistence spec that's not _very_ well-motivated and has not been really fully thought-through in a very careful way. If we ever do a replacement for `persistence.xml`, we're going to do something that is _better_ than `persistence.xml` and tightens up the whole notion of what a "persistence unit" is. But that requires very careful thought which engages with a mental model of what a persistence unit is and what its lifecycle is at development and deployment time. And I'm not seeing any of that sort of careful thinking here. I'm seeing thought bubbles and some posturing. 

So this won't go into JPA 4. We'll work on other things instead.

**Comment by gavinking** [comment]
> and that's why, at least as far as I know, essentially nobody uses `@DataSourceDefinition` except in toy examples.

In case someone might be motivated to dispute this, by the way, I searched stackoverflow for "wildfly @datasourcedefinition" and got four hits. I searched for "liberty @datasourcedefinition" and got one hit. For glassfish I got 7 hits. I searched for "datasourcedefinition" on the Hibernate forum and got zero hits.

I suppose some people might be using this annotation in tests, but I doubt that many are using it inside the Jakarta EE container.

**Comment by arjantijms** [comment]
> is specific to a given deployment of the system (those configuration parameters are always different between test/staging/prod, because test/staging/prod do not use the same database);

Which is why a decade or more ago we developed code like this:

https://github.com/omnifaces/omnipersistence/tree/develop/src/main/java/org/omnifaces/persistence/datasource

At the same time we argued for a long time to make @datasourcedefinition/data-source (in web.xml) better configurable. And we were essentialy right. 

Quarkus uses a pattern, albeit file based, that's not conceptually different. You define the data sources and basically ALL its configuration in application.properties. There is no missing unresolved dependency that a deployer somehow needs to provide at deployment time. Sure, passwords to the production database are aliased, and URLs _can_ be overriden, but only if necessary.

The point is that the core data source definition lives within the application, making it a common point of reference for devOps teams or seperate dev and ops teams, while only some sensitive details can be provided later.

This is exactly the idea behind @datasourcedefinition/data-source (in web.xml). I'm sorry that you have to think we are not carefully thinking about this. A few of us here have been in Jakarta spec development for a long time, leading discussions, weighing long term support and platform impact, and spending countless hours on the platform TCKs to make sure it all works. The names I see participating here are not the end users that suggest things on a whim type of people.

On a personal level, next to my specification work and GlassFish maintenance, I consult and have consulted for quite a few companies and organisations with large real world Jakarta EE installations. The pattern that you put away as a toy example that allegedly nobody uses has been in these production systems for a long time. One of the recent companies I consulted for have over 400 Java engineers and literally billions of dollars flow through there systems. And they are using the exact pattern described here.

**Comment by gavinking** [comment]
If "essentially all of its configuration" is in a properties file (or in XML, or whatever), what then is the purpose of the annotation?

I mean, it's not as if it expresses any relationship between the data source and the annotated type! That's just not its semantics.

Sorry, but that annotation contributes nothing useful and have never once seen a program which uses it.

**Comment by gavinking** [comment]
I mean if the point is just to declare a requirement which must be satisfied for a component to function correctly, then in Jakarta EE, that is expressed either by:

```java 
@Inject DataSource datasource;
```

Or by the old-style `@Resource` annotation.

The `@DataSourceDefinition` annotation does not even express that much; it does not even say how the data source relates to my program in any way.

**Comment by hantsy** [comment]
> is specific to a given deployment of the system (those configuration parameters are always different between test/staging/prod, because test/staging/prod do not use the same database);

Yes, Spring also faces the same problem, so we are back to the above problem circle, if the properties support EL, switching env becomes easy. ):

**Comment by hantsy** [comment]
> Sorry, but that annotation contributes nothing useful and have never once seen a program which uses it.

I think there is a purpose of using it to replace the application server tools(command line or administration console UI) to create container managed resources.

**Comment by gavinking** [comment]
> Yes, Spring also faces the same problem, so we are back to the above problem circle, if the properties support EL, switching env becomes easy. ):

I do not understand how it is that you imagine that "EL" solves this problem. That's simply magical thinking.

The EL has to get its values from somewhere, and now we're straight back to the same problem.

**Comment by gavinking** [comment]
Suppose I write:

```java
@DataSourceDefinition(
    user = "${libraryDatasource.user}",
    password = "${libraryDatasource.password}",
    url = "${libraryDatasource.url},
    maxPoolSize = 100; // can't use EL here because it's an int
    maxIdleTime = 10000; // can't use EL here because it's an int
)
```

Now:

- where does it fill in the values for `libraryDatasource.user`, `libraryDatasource.password`, `libraryDatasource.url` from?
- how do I tune the connection of my connection pool by overriding the pool size and idea time?

The only reasonable answer to these questions is: there's some other properties file or whatever (for the sake of argument, let's call it `application.properties`) where I have specified this information.

_And so what on God's green earth is the purpose of the annotation?_

That annotation buys me a big fat literal zero.

**Comment by arjantijms** [comment]
> That annotation buys me a big fat literal zero.

It’s not so much about it being an annotation. The equivalent data-source element in web.xml works the same way.

Maybe asks your friends from Quarkus where the production database settings are typically defined?

Don’t get me wrong; I agree with the core of your point: if resource definitions (whether annotation-based or web.xml) cannot be parameterized and overridden in a portable way, they won’t meet real operational needs.

The value I’m after is not “annotations for their own sake,” but having a canonical resource definition (identity + defaults) that can be bound to environment-specific values at deploy time. In practice, like I basically said above, teams already do this via framework config, server admin tooling, or custom glue, but it’s non-portable.

So I think the real spec question is: do we want a standardized configuration binding/override mechanism for resource definitions in Jakarta EE (e.g., integrating with MicroProfile Config or a platform-defined substitution model), including non-String types like pool sizes? If the answer is “no,” then I agree declarations alone don’t move the needle.

**Comment by hantsy** [comment]
> where does it fill in the values for libraryDatasource.user, libraryDatasource.password, libraryDatasource.url from?

It can be env variables, and switched in different deployment. 

For example, even without adding Config, we can set up env access via EL globally, eg. `env['DATASOURCE_USER']`, `env['DATASOURCE_PASSWORD']`, `env['DATASOURCE_URL']`, or something similar to this.

For development, it is easy to set up env via Docker. 
For production, it can be system env or equivalent.

So via this way it simply switches different envs. In Spring development stage, it is more simple, which will autoconfigure the application properties with testcontainers, when going to production, just set up the env.

**Comment by hantsy** [comment]
> It’s not so much about it being an annotation. The equivalent data-source element in web.xml works the same way.

If we split the project into small modules, and we do not access the web/web.xml in a data access module, this way is not so good.

**Comment by hantsy** [comment]
Currently in my demo projects, I think it was only used for replacing the resource creation via application serer command line or administration console UI. 

In my mind, it provides a **simple and portable** way to declare container managed resources in different application servers during the application deployment stage, no need to run GF specific `asadmin` or WildFly `JBoss cli`.

**Comment by gavinking** [comment]
> Maybe asks your friends from Quarkus where the production database settings are typically defined?

I mean, I don't have to ask anyone, this is all well documented: you set up a datasource (or a persistence unit) using properties files, system properties, environment variables, etc. And the model is actually rather flexible: 

https://quarkus.io/guides/config-reference

It's not the case that you have to have a single monolithic `application.properties` with no overriding. It's definitely not the case that these properties are compiled into your Java code.

In fairness, however, I should note that some things are a lot less flexible in Quarkus than in say WildFly, because quite a lot of "configuration" gets compiled into your image as part of the build process, in order to accelerate system startup. When you build a native image, you're essentially building the program in an "already-deployed" state.

> The value I’m after is not “annotations for their own sake,” but having a canonical resource definition (identity + defaults) that can be bound to environment-specific values at deploy time.

This I understand. I get that you might want to say that "my program depends on having a datasource with the logical name `LibraryDB`. 

The thing is that (go read the Javadoc if you doubt me) _that's simply not what `DataSourceDefintion` is_. 

Now, Jakarta EE does have an annotation like that; it's `@Resource`.

>  do we want a standardized configuration binding/override mechanism for resource definitions in Jakarta EE

Of course we do! As you can see from my comments above from a year ago, I hope that Jakarta Config will eventually provide this, but I'm beginning to lose confidence in that. Or at least, I doubt it will be ready for JPA 4.

What I am saying, though, is that EL in annotations is just not going to help solve this problem, *with or without a Config spec*. As you can see from my code above, EL crashes and burns on, like, the second thing I tried (the JDBC connection pool size). That's not a trivial objection; it shows that EL in annotations is deeply unsuited to the task.

And so that's why I tried proposing something as a sort of [reasonable intermediate solution](https://github.com/jakartaee/persistence/pull/861) that opens the door to nice integration with Jakarta Config if and when it finally exists. (But you guys didn't like that proposal, so now it's on ice.)

**Comment by gavinking** [comment]
> > where does it fill in the values for `libraryDatasource.user`, `libraryDatasource.password`, `libraryDatasource.url` from?
>
> It can be env variables, and switched in different deployment.

So then you're defining your datasource using environment variables, not using the annotation.

> For development, it is easy to set up env via Docker.
> For production, it can be system env or equivalent.

If, as you admit, this information varies between dev and prod (and staging, etc), it doesn't go in the Java code. It goes somewhere else.

I simply don't understand why you're tripling down on this.

Information like:

-  database passwords, 
- server ports, 
- host names, 
- connection pool sizes
- essentially all the other members of `@DataSourceDefinition`
 
is simply, by nature, not information that you need or want to compile into your Java code. And it definitely doesn't belong in an annotation declared `@Target(TYPE)`. Because which Java type does it relate to???

So, sure, go ahead, specify that information an environment variables, properties files, XML, whatever. I don't care. Just not in Java.

**Comment by gavinking** [comment]
> In my mind, it provides a simple and portable way to declare container managed resources in different application servers during the application deployment stage, no need to run GF specific `asadmin` or WildFly JBoss cli.

No, it just doesn't.

For that you need a Jakarta Config spec.

**Comment by arjantijms** [comment]
> It's not the case that you have to have a single monolithic application.properties with no overriding. It's definitely not the case that these properties are compiled into your Java code.

There's several axis in this discussion that may get confused.

We have 

* XML vs Annotations vs programmatic config 
* Config embedded into the application (war, runnable jar, image, whatever)
* Standard config format vs a proprietary config format

**Comment by arjantijms** [comment]
> So then you're defining your datasource using environment variables, not using the annotation.


Typically I see teams defining their data sources fully within the application, and then ONLY aliasing the password.

Whether it's an annotation or xml file or properties file is largely irrelevant in that case.

For a change to the config, the team commits updated config in the source repo that generates a deployable , the pipelines build a new app version, which is subsequently deployed.

One company I consulted for used server.xml in open liberty for this, others used application.properties in Quarkus, and yet others used data-source in web.xml for this.

I’m not proposing application-packaged datasource definitions as the only model. 

I’m proposing them as portable defaults, with a container-defined override/replace mechanism (admin config/JNDI/deployment-time configuration; fully replacing the application defined datasource with a container administered one or only overriding individual properties) that has explicit precedence and well-defined conflict behavior. Without that override model, I agree declarations alone add little.

You asked a couple of times; if the container can override everything, why have the default in the app at all?

Let me enumerate;

 * app repo as single source of truth with only the secrets overridden/provided
 * it provides a canonical reference for dev/test
 * documentation of expected properties (shape)
 * a baseline that reduces per-environment boilerplate,
while still allowing ops to harden/tune production.

**Comment by gavinking** [comment]
Honestly I have no idea why you're even continuing to argue, nor do I understand *what* you're trying to argue anymore.

1. Clearly, it's necessary to allow people to override JDBC URLs, connection pooling config, database credentials, and so on at deployment time. Nothing you can possibly say will change this simple fact.

2. The `@DataSourceDefinition` annotation, as it exists today, provides no standard way to do that, even if one were to add EL interpolation into the mix. And, of course, EL interpolation in `@DataSourceDefinition` is definitely not a standard part of the Jakarta platform

That is the bottom line, no matter how hard you wave your hands.

Anyway, we're not adding an annotation to declare persistence units in JPA 4. End of discussion.

**Comment by OndroMih** [comment]
I get your point, @gavinking , and you’re right. All would be much better solved by Jakarta Config. It’s just ao frustrating that it hasn’t been added to Jakarta EE yet. Then we try to invent solutions like annotations or EL in annotations in standalone specs that allow some common scenarios in a standard way but they are far from perfect.

I think we should all focus on getting Jakarta Config to Jakarta EE and revisit this discussion in JPA later, when we can create a solution based on Config.

**Comment by hantsy** [comment]
I think all of these are important for developers:
1.  Config properties file directly. eg. configuring all properties with a prefix for `Datasource`, and also exposes CDI bean, like Spring Boot does for the built-in beans. In background, Spring boot provides a lot of programmatic autoconfiguration codes to serve the bean producing.
2.  Annotations(read config values via EL), eg. config/env vars only provides property values (url, username, password), create the `DataSource` resource/CDI beans via `@DataSourceDefinition`.
3.  xml(legacy, also can read config values via EL), eg. the current persistence.xml to serve `PersistenceUnit`
4.  Programmatic java codes (also can read config values via `@ConfigProperty`/`@Value`, or a global `Environment`(spring), or a backed pojo `DataSourceProperies`), eg. the current `PersistenceUntiConfiguration` API. More simply, the spec specific Configuration API should be CDI ready. eg. if the persistence configuration bean is discovered, then produce `EntityManager`/`EMF` automatically.

As time goes by, personally, I think 1 and 4 will satisfy the development requirements. 

Currently, **the annotations way (such as DataSource, JMSConnectionFactor/Destination, Security and Concurrent annotations) almost covers all required resource declaration in the Jakarta EE containers**. 

I think it is not so soon that all specs are ready for Config properties/Programmatic API.

My initial request in this issue is just adding an annotation for persistence to **align with the existing annotations** and provide **consistent experience** and **transitional plan** to developers *before Config is available and integrated tightly for all specs*.

**Comment by hantsy** [comment]
> So then you're defining your datasource using environment variables, not using the annotation.

Define the properties via env variables, not means it created the DataSource managed resources/CDI beans for developers.

**Comment by hantsy** [comment]
> 
> >    For development, it is easy to set up env via Docker.
> >    For production, it can be system env or equivalent.
> 
> If, as you admit, this information varies between dev and prod (and staging, etc), it doesn't go in the Java code. It goes somewhere else.
> I simply don't understand why you're tripling down on this.

For example, in development, I setup the env vars in the docker compose file, then the annotations attribute value is set via env name will get the value from the local Docker env. 

For production, the env vars may be in system var or K8s some where, for developers we do not care, most of time it is managed by system admin/ops. The annotations use the same env name, but get different values from the production environment. Thus from development to production, we do not need to change the env name, and the env values are different for different deployment environments. This approache make our codes portable for environments, not need to recompile for the hard coded attribute values in the current annotations(besides the security annotations, others do not support EL).

**Comment by gavinking** [comment]
> My initial request in this issue is just adding an annotation for persistence to align with the existing annotations and provide consistent experience and transitional plan to developers before Config is available ...

Alright, so if I understand what you're saying here, you're asking for a temporary stop-gap solution.

But stop-gaps don't belong in Jakarta specifications.

I don't think you fully understand that when I write something down in the Persistence spec, _it's still going to be there in twenty years_, and my colleagues who maintain Hibernate are still going to be maintaining the implementation of that feature.

> I think all of these are important for developers:
> 1. Config properties file directly. eg. configuring all properties with a prefix for Datasource, and also exposes CDI bean, like Spring Boot does for the built-in beans. In background, Spring boot provides a lot of programmatic autoconfiguration codes to serve the bean producing.
> 2. Annotations(read config values via EL), eg. config/env vars only provides property values (url, username, password), create the DataSource resource/CDI beans via @DataSourceDefinition.
> 3. xml(legacy, also can read config values via EL), eg. the current persistence.xml to serve PersistenceUnit
> 4. Programmatic java codes (also can read config values via @ConfigProperty/@Value, or a global Environment(spring), or a backed pojo DataSourceProperies), eg. the current PersistenceUntiConfiguration API. More simply, the spec specific Configuration API should be CDI ready. eg. if the persistence configuration bean is discovered, then produce > EntityManager/EMF automatically.
> 
> ... and integrated tightly for all specs
> For example, in development, I setup the env vars in the docker compose file, then the annotations attribute value is set via env name will get the value from the local Docker env.
> For production, the env vars may be in system var or K8s some where, for developers we do not care, most of time it is managed by system admin/ops. The annotations use the same env name, but get different values from the production environment. Thus from development to production, we do not need to change the env name, and the env values are different for different deployment environments. This approache make our codes portable for environments, not need to recompile for the hard coded attribute values in the current annotations(besides the security annotations, others do not support EL).

Do you know what I would like? I would like a magical pony that shrinks down to the size of a penny so I can keep him in my pocket for whenever I need to ride him home. Also, he would be a magical talking pony who would keep me company when I get lonely. Oh and also he would make rainbows even at nighttime.

Frustratingly, such a beast is disallowed by the laws of nature. There are no magical ponies, only real ponies who eat hay and shit.

None of what you've written above comes remotely close to being a proposal for something I could possibly write down in the Persistence spec and then implement in Hibernate, and expect my colleagues to maintain for the next two decades.

**Comment by gavinking** [comment]
> provide consistent experience

Wait wait wait wait wait. 

Perhaps I've misunderstood what it is you really want.

> consistent experience

OK, so here's a straightforward way we could provide you with a consistent, completely portable way to define a datasource and a persistence unit which depends on it:


```xml
<persistence xmlns="https://jakarta.ee/xml/ns/persistence"
             xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
             xsi:schemaLocation="https://jakarta.ee/xml/ns/persistence
    https://jakarta.ee/xml/ns/persistence/persistence_4_0.xsd"
             version="4.0">

    <persistence-unit name="Library" transaction-type="JTA">
        <description>My example persistence unit</description>
        <jta-data-source>
            <url>jdbc:postgresql://localhost/library</url>
            <user>gavin</user>
            <password>p0ny</password>
            <max-pool-size>100</max-pool-size>
            <max-idle-time>10000</max-idle-time>
        </jta-data-source>
        <class>org.example.Book</class>
        <class>org.example.Author</class>
        <class>org.example.Publisher</class>
        <exclude-unlisted-classes/>
        <default-fetch-type>LAZY</default-fetch-type>
        <shared-cache-mode>ENABLE_SELECTIVE</shared-cache-mode>
    </persistence-unit>
</persistence>
```

We could also support this variation:

```xml
<persistence xmlns="https://jakarta.ee/xml/ns/persistence"
             xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
             xsi:schemaLocation="https://jakarta.ee/xml/ns/persistence
    https://jakarta.ee/xml/ns/persistence/persistence_4_0.xsd"
             version="4.0">

    <persistence-unit name="Library" transaction-type="JTA">
        <description>My example persistence unit</description>
        <jta-data-source>jdbc/library</jta-data-source>
        <class>org.example.Book</class>
        <class>org.example.Author</class>
        <class>org.example.Publisher</class>
        <exclude-unlisted-classes/>
        <default-fetch-type>LAZY</default-fetch-type>
        <shared-cache-mode>ENABLE_SELECTIVE</shared-cache-mode>
    </persistence-unit>

    <jta-data-source>
        <name>jdbc/library</name>
        <description>My example persistence datasource</description>
        <url>jdbc:postgresql://localhost/library</url>
        <user>gavin</user>
        <password>p0ny</password>
        <max-pool-size>100</max-pool-size>
        <max-idle-time>10000</max-idle-time>
    </jta-data-source>
</persistence>
```

That is something that would be truly convenient, and incredibly easy to add.

**Comment by gavinking** [comment]
Note that the above suggestion implicates almost no work on the part of Jakarta EE implementors who already support `@DataSourceDefinition`, since we would give `<jta-data-source>` almost exactly the same members, with exactly the same semantics, as `@DataSourceDefinition`.

**Comment by gavinking** [comment]
I have opened #864, since this thread is a complete mess.

**Comment by sebersole** [comment]
> That is something that would be truly convenient, and incredibly easy to add.

As we discussed off line, I do like this assuming we get EE containers to buy in.  The ability to define this in a environment-portable way would be very nice indeed for applications leveraging JPA.

**Comment by beikov** [comment]
The discussion around configuration of the datasource is roughly finished now it seems and defining the data source in the XML descriptor seems like a viable solution for Jakarta EE and Java SE.

Defining a container managed persistence unit via annotation instead of persistence.xml sounds ok to me and AFAICT, would simply be a different definition format, so all the same limitations apply like they do with the persistence.xml. I guess that the definition with annotations is going to be as clunky/"elegant" as via XML (thinking about nested annotations), but what bothers me a bit is the fact that there is no good place to put the annotation. Putting the annotation on `PACKAGE` or `MODULE` would be ok, but putting it on `TYPE` like `@DataSourceDefinition` simply sounds wrong to me.

Since this would be a Jakarta EE only feature, I'd support the effort to add this if someone provides a PR for it.

**Comment by hantsy** [comment]
@beikov Yes, as mentioned before, I would like to use such an annotation similar to other existing XXXDefinition to declare a container managed Persistence Unit resource (also exposed as CDI beans like concurrency and security annotations). 

It is simple and clear.

**Comment by gavinking** [comment]
So my final conclusion after these very long discussions is the following.

Any proposal for a replacement for `persistence.xml`, either [with](https://github.com/jakartaee/persistence/issues/701) or [without](https://github.com/jakartaee/persistence/issues/870) some kind of [`@PersistenceModule` annotation](https://github.com/jakartaee/persistence/pull/861) is going to have two address two main concerns:

1. how/where to specify non-static configuration, and
2. how to smoothly transition between the Jakarta container environment and the standalone mode.

There are a wide range of possible answers to question 1:

- a `persistence.properties` or `unit-name.properties` file
- JVM system properties
- a set of standard environment variables
- a YAML file
- a TOML file
- etc
- Jakarta Config

Let's go down the list

- For a lot of reasons, but mainly because I find `hibernate.properties` to be a very comfortable experience, I myself would be perfectly happy with the first option on the list. 
- I don't really have much of an opinion on system properties or environment variables, but as far as I know other Jakarta specs don't talk about such things, and so it would be weird for the Persistence spec to be the first to go there.
- I've never heard of anyone ask for YAML or TOML, and my understanding is that they're still not extremely popular in Java. It would of course be easy to define a YAML format isomorphic to `persistence.xml` but I really don't know what would be gained by doing so if nobody is asking for this.
- Jakarta Config is still an unknown quantity, which hangs a huge question mark over any decision we might take in this group, and might obsolete whatever we do here in the short to medium term.

It's clear that even after so much back and forth, we're nowhere near a consensus on any one particular approach. In the meantime, #864 is a very reasonable enhancement to `persistence.xml` that improves usability, and at least centralizes all the XML in one place.

I want to reemphasize that, fashions aside, there's absolutely nothing wrong with `persistence.xml`. I was one of the original guys rebelling against the overuse of XML in J2EE, in the Spring framework, and in Hibernate and other Java technologies in general, but this particular use of XML is _not_ a misuse and I don't see any particular problem with it.

In light of the lack of consensus, and the unlikelihood of reaching consensus, I'm going to close these two issues.

When Jakarta Config actually exists, or, alternatively, if it becomes clear that Jakarta Config is never going to happen, we can come back and ask if we need to design a replacement for `persistence.xml`. But it seems the time is not ripe, and we already have a LOT on our plate for JPA4.
